version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ifd579123 
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
